name: Build Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build mod
    uses: geode-sdk/build-geode-mod/.github/workflows/build.yml@main
    with:
      combine: true

  package:
    name: Package builds
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: geode-sdk/build-geode-mod/package@main
        with:
          build-output: ${{ needs.build.outputs.build-output }}
